### ISSUE TITLE
lemma_char_idx

### ISSUE THREAD

**Issue by emanjavacas** [hipster-philology/pandora#15]
I am trying out both models for config with `lemma == 'generate'` and there seems to be a bug in preprocessing:

```
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    tagger.setup_to_train(train_data=train_data, dev_data=dev_data)
  File "/home/enrique/code/python/pandora/pandora/tagger.py", line 321, in setup_to_train
    self.save()
  File "/home/enrique/code/python/pandora/pandora/tagger.py", line 410, in save
    self.preprocessor.save(self.model_dir)
  File "/home/enrique/code/python/pandora/pandora/preprocessing.py", line 655, in save
    for idx, c in self.lemma_char_idx.items():
AttributeError: 'Preprocessor' object has no attribute 'lemma_char_idx'
```

I started checking this out and it seems there is an issue with the naming of a couple of variables involving "lemma_char_idx", "lemma_char_vocab", and "lemma_char_lookup".

Perhaps @mikekestemont can have a look at this?

I had to add some other changes so make sure you pull first from the pytorch branch.

That part of the code also looks a bit brittle given all the `if self....`-statements that make it hard to keep track of things while debugging, perhaps some refactoring could come fine.

**Comment by mikekestemont** [comment]
Sigh... My bad. I can look into this on Wednesday. In the meanwhile: the
characters of the lemmas are also given as full one-hot matrices in the
case of include_lemma="generate". Doesn't that pose the same problem as
with the one-hot encoding for include_lemma='label?'

Prof. Dr. Mike Kestemont | www.mike-kestemont.org | Twitter:
@Mike_Kestemont | mike.kestemont@uantwerp.be | mike.kestemont@gmail.com |
University of Antwerp | City Campus, Prinsstraat 13, room D. 118 I B-2000
Antwerp, Belgium | tel. +32 (0)3 265.42.54

> Check out our documentary on Digital Humanities and Hildegard of Bingen:
watch it in HD on Vimeo: https://vimeo.com/70881172

On Mon, May 8, 2017 at 3:28 PM, Enrique Manjavacas <notifications@github.com

**Comment by emanjavacas** [comment]
Indeed, I had assumed that binarization only occurs when to_categorical is called, but it seems `vectorize_lemma` it also doing this. I guess the same approach should work. I'll add an option specifying the desired output type.

**Comment by emanjavacas** [comment]
Also, is there any reason why `vectorize_lemmas` uses `float32` (as opposed to integers)?

**Comment by mikekestemont** [comment]
Float32 is required for calculating the categorical crossentropy in keras.
As to the may self.-variables: I agree that this is a mess. Would it oerhaps make more sense to load the params in a separate module which is all imported by all other modules, so that we have these available as a sort of static variable at the app-levelv

**Comment by emanjavacas** [comment]
Yes, something like that would be fine

**Comment by emanjavacas** [comment]
- [ ] Check where the binarization is happening inside client code
- [ ] Move it out and into impl/keras/...

**Comment by emanjavacas** [comment]
I added the categorical option to Preprocessor, but there is still an error due to the fact that lemma_char_idx doesn't seem to be added to the object itself. Could you @mikekestemont  look into it?

**Comment by jedgusse** [comment]
Hi @mikekestemont, I had a look on the train to the bug, could it be that the `lemma_char_idx` is supposed to cover the `char_vocab` dictionary that is returned from `def index_characters()`? Apparently the dictionary's supposed to contain indices to decode the predictions to lemmas.

**Comment by jedgusse** [comment]
Yeah I think `self.lemma_char_idx` was an unwanted alias for `self.lemma_char_lookup`.

**Comment by PonteIneptique** [comment]
@jedgusse @mikekestemont @emanjavacas It would be greatly appreciated, for future development, that ivar would be documented such as 

```python
class A(object):
    """
    :ivar x: some description
    :type x: type
    """
    def __init__(self, x):
        self.x = x
```

and that they'd be created on initiation, even though they could be empty. This would avoid this kind of situation in the future :)

**Comment by mikekestemont** [comment]
Thanks @jedgusse that must have been it (silly naming error when refactoring). I have pushed a fix but I haven't been able to test it yet, because I ran into a new issue, ie that the keras load function isn't static yet. I'll fix that in the evening.

**Comment by mikekestemont** [comment]
This should be solved by my latest commits in the pytorch branch.
@jedgusse @emanjavacas can you verify?

**Comment by emanjavacas** [comment]
seems to be fixed.
I am still wondering about the float issue. Currently lemma targets are encoded as floats (so I have to convert back to ints inside the pytorch model (which isn't too nice). You said, keras needs floats for the cross-entropy loss, but how come all other targets (pos and morph) do get ints? Their losses is also a crossentropy, right?

**Comment by mikekestemont** [comment]
Are we talking about the way tokens are inputted on a character by
character basis? I could also make the keras models depend on embeddings
for the characters? Would that be easier?

**Comment by emanjavacas** [comment]
Mmh, I just mean that the lemma targets are floats, where as pos targets are integers. By target I mean the true label input to the cross entropy loss.

**Comment by mikekestemont** [comment]
can I close this @emanjavacas ?

**Comment by emanjavacas** [comment]
I think there still unresolved issues here, the float,int thing especially:

`I am still wondering about the float issue. Currently lemma targets are encoded as floats (so I have to convert back to ints inside the pytorch model (which isn't too nice). You said, keras needs floats for the cross-entropy loss, but how come all other targets (pos and morph) do get ints? Their losses is also a crossentropy, right?`

**Comment by emanjavacas** [comment]
Any progress here?

**Comment by mikekestemont** [comment]
I can have a look at this tomorrow.
