### ISSUE TITLE
How to handle gpu

### ISSUE THREAD

**Issue by emanjavacas** [hipster-philology/pandora#47]
We should pass params to the model defining whether to use gpu and which gpu to use.

**Comment by PonteIneptique** [comment]
Could we have by default some kind of autodetect ? This would make sense for the CLI at least.

**Comment by emanjavacas** [comment]
Sure, it could be part of the model interface, since this is framework
dependent.

**Comment by PonteIneptique** [comment]
I might have an issue with GPU actually : 
```
Traceback (most recent call last):
  File "/home/thibault/dev/pandora-dev/env/bin/pandora-train", line 11, in <module>
    load_entry_point('pandora', 'console_scripts', 'pandora-train')()
  File "/home/thibault/dev/pandora-dev/pandora/cli.py", line 144, in cli_train
    train_func(**vars(parser.parse_args()))
  File "/home/thibault/dev/pandora-dev/pandora/cli.py", line 112, in train_func
    tagger.epoch(autosave=True, eval_test=tagger.include_test)
  File "/home/thibault/dev/pandora-dev/pandora/tagger.py", line 496, in epoch
    self.model.epoch(train_in, train_out)
  File "/home/thibault/dev/pandora-dev/pandora/impl/pytorch/model.py", line 290, in epoch
    src, trg = batches[batch]
  File "/home/thibault/dev/pandora-dev/pandora/impl/pytorch/utils.py", line 50, in __getitem__
    src = src.cuda()
AttributeError: 'dict' object has no attribute 'cuda'
```

when setting gpu to True

**Comment by emanjavacas** [comment]
I haven't tested on the GPU yet. I will work on that and hopefully we will
have a way to do GPU detection for the interface

**Comment by emanjavacas** [comment]
I've added discovery mechanism to pytorch model
