### ISSUE TITLE
Cannot run PyTorch

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora#48]
Message I have when running the cli 

```shell
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Couldn't import PyTorch. PyTorch implementation not available
```

Pip Freeze 
```shell
boto==2.48.0
bz2file==0.98
certifi==2017.7.27.1
chardet==3.0.4
cycler==0.10.0
editdistance==0.3.1
gensim==2.0.0
h5py==2.7.0
idna==2.6
Keras==2.0.4
matplotlib==2.0.2
mock==2.0.0
nltk==3.2.2
numpy==1.12.1
olefile==0.44
pandas==0.20.3
-e git+git@github.com:hipster-philology/pandora.git@8f71dbca8d9d5eb335eb43ed9fb17705d65b5113#egg=pandora
pbr==3.1.1
Pillow==4.2.1
protobuf==3.4.0
pyparsing==2.2.0
python-dateutil==2.6.1
pytz==2017.2
PyYAML==3.12
requests==2.18.4
scikit-learn==0.18.1
scipy==0.19.1
seaborn==0.7.1
six==1.11.0
smart-open==1.5.3
tensorflow-gpu==1.1.0
Theano==0.9.0
torch==0.2.0.post3
torchvision==0.1.9
urllib3==1.22
Werkzeug==0.12.2

```

**Comment by PonteIneptique** [comment]
Following on this : 
```
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from pandora.cli import cli_train
  File "/home/thibault/dev/pandora-dev/pandora/cli.py", line 5, in <module>
    from pandora.tagger import Tagger
  File "/home/thibault/dev/pandora-dev/pandora/tagger.py", line 14, in <module>
    from pandora.impl import KerasModel, PyTorchModel
  File "/home/thibault/dev/pandora-dev/pandora/impl/__init__.py", line 4, in <module>
    raise E
  File "/home/thibault/dev/pandora-dev/pandora/impl/__init__.py", line 2, in <module>
    from pandora.impl.pytorch.model import PyTorchModel
  File "/home/thibault/dev/pandora-dev/pandora/impl/pytorch/model.py", line 9, in <module>
    import torch
  File "/home/thibault/dev/pandora-dev/env/lib/python3.5/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
```

**Comment by mikekestemont** [comment]
is this the most recent version of numpy?

**Comment by PonteIneptique** [comment]
I simply wrote the list of issue and just proposed a fix ;)
