### ISSUE TITLE
Training with include_morph = label yiels TypeError: to_categorical() got an unexpected keyword argument 'nb_classes'

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [hipster-philology/pandora#67]
This is similar to the bug described in #12 . When I launch training on the Geste sample data, with
````python
include_morph = label
````
in the config, I get the following error,
````
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    cli_train()
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/cli.py", line 144, in cli_train
    train_func(**vars(parser.parse_args()))
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/cli.py", line 94, in train_func
    tagger.setup_to_train(**data_sets)
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/tagger.py", line 230, in setup_to_train
    morph=self.train_morph)
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/preprocessing.py", line 516, in transform
    X_morph, nb_classes=len(self.morph_encoder.classes_))
TypeError: to_categorical() got an unexpected keyword argument 'nb_classes
````

This does not happen, though, with
````python
include_morph = multilabel
````
which seems to work quite fine (I'm actually impressed by the results obtained with this option).

**Comment by mikekestemont** [comment]
Can you close this, if the PR satisfactory @Jean-Baptiste-Camps ?

**Comment by PonteIneptique** [comment]
You PRed the wrong repo @mikekestemont :)
