### ISSUE TITLE
Tagger.py fails with pytorch model

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora#92]
I tried the tagger with 12c_x but it seems to have an issue loading the right implementation model : 

```
python tagger.py  --input "Cogito ergo sum" --string models/12c_x
Using TensorFlow backend.
2017-11-05 14:03:35,199 : INFO : 'pattern' package not found; tag filters are not available for English
::: started :::
Using params from config file: models/12c_x/config.txt
Re-loading preprocessor...
Re-loading pretrainer...
Re-building model...
Traceback (most recent call last):
  File "tagger.py", line 6, in <module>
    cli_tagger()
  File "/home/thibault/dev/pandora-dev/pandora/cli.py", line 253, in cli_tagger
    tag_string(**vars(args))
  File "/home/thibault/dev/pandora-dev/pandora/cli.py", line 206, in tag_string
    tagger = Tagger(load=True, model_dir=model, overwrite=kwargs)
  File "/home/thibault/dev/pandora-dev/pandora/tagger.py", line 143, in __init__
    self.load()
  File "/home/thibault/dev/pandora-dev/pandora/tagger.py", line 167, in load
    include_morph=self.include_morph)
  File "/home/thibault/dev/pandora-dev/pandora/impl/keras/model.py", line 317, in load
    with open(os.path.join(model_dir, 'model_architecture.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/12c_x/model_architecture.json'
```

**Comment by PonteIneptique** [comment]
The bug seems to be that it tries to load PyTorch model through Keras.

**Comment by PonteIneptique** [comment]
I tracked down the bug : model= PyTorch is not exported to the modelIdr/config.txt :)
